# Generated by Django 4.2.7 on 2025-10-01 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField(default=22)),
                ('node_type', models.CharField(choices=[('server', 'Server'), ('website', 'Website'), ('database', 'Database'), ('application', 'Application')], default='server', max_length=50)),
                ('auth_key', models.TextField(help_text='SSH key or API key for authentication')),
                ('username', models.CharField(default='root', max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('platform_version', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_cores', models.IntegerField(blank=True, null=True)),
                ('total_memory', models.BigIntegerField(blank=True, help_text='Total RAM in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen', 'name'],
                'unique_together': {('hostname', 'ip_address', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='NodeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=255)),
                ('is_running', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('config_path', models.CharField(blank=True, max_length=500, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.node')),
            ],
            options={
                'unique_together': {('node', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='NodeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('cpu_load_avg', models.JSONField(blank=True, null=True)),
                ('memory_used', models.BigIntegerField()),
                ('memory_total', models.BigIntegerField()),
                ('memory_percent', models.FloatField()),
                ('swap_used', models.BigIntegerField(blank=True, null=True)),
                ('swap_percent', models.FloatField(blank=True, null=True)),
                ('disk_usage', models.JSONField(default=dict)),
                ('network_bytes_sent', models.BigIntegerField(blank=True, null=True)),
                ('network_bytes_recv', models.BigIntegerField(blank=True, null=True)),
                ('network_connections', models.IntegerField(blank=True, null=True)),
                ('process_count', models.IntegerField(blank=True, null=True)),
                ('full_metrics', models.JSONField(default=dict)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='services.node')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['node', '-timestamp'], name='services_no_node_id_065c91_idx')],
            },
        ),
        migrations.CreateModel(
            name='NodeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='services.node')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['node', 'resolved', '-created_at'], name='services_no_node_id_dd34f4_idx')],
            },
        ),
    ]
