# Generated by Django 4.2.7 on 2025-10-03 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_domaincheck_domain_delete_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_node_nodeservice_nodemetrics_nodealert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('registrar', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('active', 'Active'), ('warning', 'Warning'), ('critical', 'Critical'), ('expired', 'Expired'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('check_interval_hours', models.IntegerField(default=24)),
                ('notification_days', models.IntegerField(default=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, help_text='TXT record verification token', max_length=255)),
                ('verification_status', models.CharField(blank=True, help_text='Current verification status', max_length=50)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('web_root', models.CharField(blank=True, help_text='Web root directory on the server', max_length=500)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ssl_expiry', models.DateTimeField(blank=True, null=True)),
                ('dns_records', models.JSONField(blank=True, help_text='Store DNS records for reference', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_server', models.ForeignKey(blank=True, help_text='Server hosting this domain (automatically converts server to webserver type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='dashboard.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='DomainCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expiry_date_found', models.DateTimeField(blank=True, null=True)),
                ('registrar_found', models.CharField(blank=True, max_length=100)),
                ('check_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('whois_data', models.JSONField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='services.domain')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['domain', '-timestamp'], name='services_do_domain__fa7018_idx'), models.Index(fields=['-timestamp'], name='services_do_timesta_29b612_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['expiry_date'], name='services_do_expiry__7791e9_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['user', 'is_active'], name='services_do_user_id_d5e5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['status'], name='services_do_status_9b474e_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['linked_server'], name='services_do_linked__15666e_idx'),
        ),
    ]
