# Generated by Django 5.2.6 on 2025-10-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_domain_domaincheck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
