# Generated by Django 5.2.6 on 2025-11-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_secret_secretversion_secretproject_secretenvironment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='ssh_key_id',
            field=models.CharField(blank=True, help_text='Key ID for retrieving SSH password from secret manager', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='ssh_port',
            field=models.IntegerField(default=22, help_text='SSH port for SFTP file operations'),
        ),
    ]
