# Generated by Django 5.2.6 on 2025-11-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_node_ssh_key_id_node_ssh_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretenvironment',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide from UI (for system-managed secrets)'),
        ),
    ]
