# Generated by Django 5.2.6 on 2025-11-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_secretenvironment_is_hidden'),
    ]

    operations = [
    ]
