# Generated by Django 5.2.6 on 2025-11-18

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_add_is_hidden_to_secretenvironment'),
        ('oauth2_provider', '__latest__'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretproject',
            name='application',
            field=models.OneToOneField(
                to='oauth2_provider.Application',
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name='secret_project',
            ),
        ),
    ]
