OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth2_provider.Application'
"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure logs directory exists early so FileHandler does not fail
LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-07jj1fvq#v29s9r7i%k!h0is2=l4bay1yll8o5z1=9=f5f2=ud'

import sqlite3
import secrets
from cryptography.fernet import Fernet
import base64
from hashlib import sha256

def get_encryption_key():
    key = SECRET_KEY.encode()
    hashed = sha256(key).digest()
    return base64.urlsafe_b64encode(hashed)

def encrypt_value(value):
    f = Fernet(get_encryption_key())
    encrypted = f.encrypt(value.encode())
    return base64.b64encode(encrypted).decode()

def decrypt_value(encrypted_value):
    f = Fernet(get_encryption_key())
    encrypted_bytes = base64.b64decode(encrypted_value.encode())
    decrypted = f.decrypt(encrypted_bytes)
    return decrypted.decode()

def get_or_create_db_credentials():
    """
    Generate or retrieve database credentials dynamically.
    Creates: alterion-{randomstring} user and random password
    Stores encrypted in system_secrets.db using Fernet key (memory only)
    """
    db_path = BASE_DIR / 'system_secrets.db'
    conn = sqlite3.connect(str(db_path))
    c = conn.cursor()
    c.execute('CREATE TABLE IF NOT EXISTS secrets (key TEXT PRIMARY KEY, value TEXT)')
    
    # Get or generate db_user
    c.execute('SELECT value FROM secrets WHERE key = ?', ('db_user',))
    row = c.fetchone()
    if row:
        db_user = decrypt_value(row[0])
    else:
        # Generate unique database user: alterion-{random}
        random_suffix = secrets.token_urlsafe(12).replace('-', '').replace('_', '')[:12]
        db_user = f"alterion_{random_suffix}"
        encrypted = encrypt_value(db_user)
        c.execute('INSERT INTO secrets (key, value) VALUES (?, ?)', ('db_user', encrypted))
        print(f"[INIT] Generated DB user: {db_user}")
    
    # Get or generate db_name (using server ID)
    c.execute('SELECT value FROM secrets WHERE key = ?', ('db_name',))
    row = c.fetchone()
    if row:
        db_name = decrypt_value(row[0])
    else:
        # Get serverid
        serverid_path = BASE_DIR / 'dashboard' / 'serverid.dat'
        if serverid_path.exists():
            with open(serverid_path, 'r') as f:
                serverid = f.read().strip()
        else:
            import uuid
            serverid = uuid.uuid4().hex[:16]
            serverid_path.parent.mkdir(parents=True, exist_ok=True)
            with open(serverid_path, 'w') as f:
                f.write(serverid)
        db_name = f"alterion_{serverid}"
        encrypted = encrypt_value(db_name)
        c.execute('INSERT INTO secrets (key, value) VALUES (?, ?)', ('db_name', encrypted))
        print(f"[INIT] Generated DB name: {db_name}")
    
    # Get or generate db_password
    c.execute('SELECT value FROM secrets WHERE key = ?', ('db_password',))
    row = c.fetchone()
    if row:
        password = decrypt_value(row[0])
    else:
        password = secrets.token_urlsafe(32)
        encrypted = encrypt_value(password)
        c.execute('INSERT INTO secrets (key, value) VALUES (?, ?)', ('db_password', encrypted))
        print(f"[INIT] Generated DB password (length: {len(password)})")
    
    conn.commit()
    conn.close()
    return db_user, db_name, password

DB_USER, DB_NAME, DB_PASSWORD = get_or_create_db_credentials()

import os

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-07jj1fvq#v29s9r7i%k!h0is2=l4bay1yll8o5z1=9=f5f2=ud'

# Build ALLOWED_HOSTS dynamically
# Always allow localhost, 127.0.0.1, and local network IPs
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.localhost',  # Allow all localhost subdomains
    '*',  # Allow all hosts for local development/deployment
]

# Add custom hosts from environment variable (for nginx domain setup)
# Use this to add your domain when configuring nginx
custom_hosts = os.environ.get('ALLOWED_HOSTS', '')
if custom_hosts:
    # Remove the wildcard when custom hosts are provided in production
    if '*' in ALLOWED_HOSTS:
        ALLOWED_HOSTS.remove('*')
    ALLOWED_HOSTS.extend([h.strip() for h in custom_hosts.split(',') if h.strip()])

# Server Port Configuration
PORT = 13527  # Fixed HTTPS port for Alterion Panel

# Backend WebSocket Host (for node API client)
BACKEND_WS_HOST = "wss://alterion-panel.coraldune.com"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'secretmanager',
    'channels',
    'rest_framework',
    'backend',  # Main backend app for management commands
    'dashboard.apps.DashboardConfig',
    'services',
    'django_extensions',
    'oauth2_provider',
    'accounts',
    'corsheaders',
    'sslserver',
    'pagebuilder',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'backend.middleware.Authmiddleware.AuthMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        'OPTIONS': {
            'connect_timeout': 10,
        },
    },
    'secrets': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'system_secrets.db',
    }
}

DATABASE_ROUTERS = ['backend.db_router.SecretRouter']


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ----------------------------------------------------------------------------
# Environment / Debug
# ----------------------------------------------------------------------------
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# ----------------------------------------------------------------------------
# Security & HTTPS Settings (respect reverse proxy TLS termination)
# ----------------------------------------------------------------------------
# Trust X-Forwarded-Proto header set by nginx so request.is_secure() works
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Force HTTPS redirects when not in DEBUG
SECURE_SSL_REDIRECT = not DEBUG

# Cookie security
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# HTTP Strict Transport Security (only enable when cert is valid & stable)
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Other recommended headers
SECURE_REFERRER_POLICY = 'strict-origin'
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# (CORS/CSRF dynamic expansion deferred until lists are defined below)


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration to show INFO level logs in console
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'log.log',
            'formatter': 'verbose',
        },
    },
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'root': {
        'handlers': ['file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'oauth2_provider': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'authmiddleware': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# CORS settings
# Base origins
CORS_ALLOWED_ORIGINS = [
    'https://localhost:13527',
    'https://127.0.0.1:13527',
]

# Add custom origins from environment variable
custom_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if custom_cors_origins:
    CORS_ALLOWED_ORIGINS.extend([o.strip() for o in custom_cors_origins.split(',') if o.strip()])

CORS_ALLOW_CREDENTIALS = True

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    'https://localhost:13527',
    'https://127.0.0.1:13527',
    
]

# Add custom CSRF origins from environment variable
custom_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if custom_csrf_origins:
    CSRF_TRUSTED_ORIGINS.extend([o.strip() for o in custom_csrf_origins.split(',') if o.strip()])

# After both CORS_ALLOWED_ORIGINS and CSRF_TRUSTED_ORIGINS exist, expand from ALLOWED_HOSTS
def _host_to_origin(hostname: str):
    hostname = hostname.strip()
    if not hostname or hostname == '*':
        return None
    if hostname.startswith('http://') or hostname.startswith('https://'):
        return hostname.replace('http://', 'https://')  # enforce https
    return f'https://{hostname}'

_extra_origins = [o for o in (_host_to_origin(h) for h in ALLOWED_HOSTS) if o]
for origin in _extra_origins:
    if origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(origin)
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'authentication.cookie_oauth2.CookieOAuth2Authentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# OAuth2 Provider settings
OAUTH2_PROVIDER = {
    'OAUTH2_VALIDATOR_CLASS': 'authentication.custom_oauth2_validator.CustomOAuth2Validator',
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Django Channels
ASGI_APPLICATION = 'backend.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

# Cache configuration for download progress tracking
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

