# Generated by Django 4.2.7 on 2025-10-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(default=list, help_text='JSON array of widget layout configuration')),
                ('available_widgets', models.JSONField(default=list, help_text='JSON array of available widgets in library')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_layout', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Widget Layout',
                'verbose_name_plural': 'Widget Layouts',
            },
        ),
    ]
