# Generated by Django 4.2.7 on 2025-11-11 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_widgetlayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier (fingerprint)', max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('device_name', models.CharField(blank=True, help_text='Browser and OS info', max_length=255)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('login_count', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Login',
                'verbose_name_plural': 'Device Logins',
                'ordering': ['-last_login'],
                'indexes': [models.Index(fields=['device_id', '-last_login'], name='accounts_de_device__ef4d66_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
