# Generated by Django 5.2.6 on 2025-09-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
