# Generated by Django 4.2.7 on 2025-10-01 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('database', 'Database'), ('security', 'Security'), ('deployment', 'Deployment'), ('alert_resolved', 'Alert Resolved'), ('alert_created', 'Alert Created'), ('system', 'System'), ('file', 'File'), ('config', 'Configuration'), ('backup', 'Backup'), ('service', 'Service')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.server')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='dashboard_a_timesta_77b0fd_idx'), models.Index(fields=['log_type', '-timestamp'], name='dashboard_a_log_typ_2119c8_idx'), models.Index(fields=['user', '-timestamp'], name='dashboard_a_user_id_510456_idx')],
            },
        ),
    ]
