# Generated by Django 4.2.7 on 2025-10-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alert_ignored_alert_ignored_at_alert_ignored_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='log_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('database', 'Database'), ('security', 'Security'), ('deployment', 'Deployment'), ('alert_resolved', 'Alert Resolved'), ('alert_ignored', 'Alert Ignored'), ('alert_created', 'Alert Created'), ('system', 'System'), ('file', 'File'), ('config', 'Configuration'), ('backup', 'Backup'), ('service', 'Service')], max_length=20),
        ),
    ]
