# Generated by Django 4.2.7 on 2025-10-01 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_activitylog_log_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UptimeMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('is_up', models.BooleanField(default=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('check_interval', models.IntegerField(default=300)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_monitors', to='dashboard.server')),
            ],
        ),
        migrations.CreateModel(
            name='UptimeIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('downtime', 'Downtime'), ('degraded', 'Performance Degraded'), ('maintenance', 'Planned Maintenance')], default='downtime', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_incidents', to='dashboard.server')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UptimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_up', models.BooleanField()),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_checks', to='dashboard.server')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='dashboard_u_timesta_ef1a6c_idx'), models.Index(fields=['server', '-timestamp'], name='dashboard_u_server__b55a2a_idx')],
            },
        ),
    ]
