# Generated by Django 4.2.7 on 2025-10-02 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_uptimemonitor_uptimeincident_uptimecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='server',
            name='hostname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='server_type',
            field=models.CharField(choices=[('server', 'Server'), ('webserver', 'Web Server'), ('database', 'Database Server'), ('cache', 'Cache Server'), ('storage', 'Storage Server')], default='server', max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='server',
            name='web_stats_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('registrar', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('warning', 'Warning'), ('critical', 'Critical'), ('expired', 'Expired'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('check_interval_hours', models.IntegerField(default=24)),
                ('notification_days', models.IntegerField(default=30)),
                ('web_root', models.CharField(blank=True, help_text='Web root directory on the server', max_length=500)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ssl_expiry', models.DateTimeField(blank=True, null=True)),
                ('dns_records', models.JSONField(blank=True, help_text='Store DNS records for reference', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_server', models.ForeignKey(blank=True, help_text='Server hosting this domain (automatically converts server to webserver type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='dashboard.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='DomainCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expiry_date_found', models.DateTimeField(blank=True, null=True)),
                ('registrar_found', models.CharField(blank=True, max_length=100)),
                ('check_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('whois_data', models.JSONField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='dashboard.domain')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['domain', '-timestamp'], name='dashboard_d_domain__3ade33_idx'), models.Index(fields=['-timestamp'], name='dashboard_d_timesta_8d2307_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['expiry_date'], name='dashboard_d_expiry__c2b9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['user', 'is_active'], name='dashboard_d_user_id_a49ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['status'], name='dashboard_d_status_575189_idx'),
        ),
    ]
