# Generated by Django 4.2.7 on 2025-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_server_created_at_server_description_server_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='verification_ns',
            field=models.TextField(blank=True, help_text='Nameserver verification records (JSON array)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='verification_status',
            field=models.CharField(blank=True, help_text='Current verification status', max_length=50),
        ),
        migrations.AddField(
            model_name='domain',
            name='verification_token',
            field=models.CharField(blank=True, help_text='TXT record verification token', max_length=255),
        ),
        migrations.AddField(
            model_name='domain',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
