# Generated by Django 4.2.7 on 2025-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_domain_is_verified_domain_verification_ns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('active', 'Active'), ('warning', 'Warning'), ('critical', 'Critical'), ('expired', 'Expired'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
