# Generated by Django 4.2.7 on 2025-10-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_domain_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='verification_ns',
        ),
    ]
