# Generated by Django 4.2.7 on 2025-10-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_domain_verification_ns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaincheck',
            name='domain',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='DomainCheck',
        ),
    ]
