# Generated by Django 4.2.26 on 2025-12-02 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_secrets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'secrets',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SecretVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='secretmanager.secret')),
            ],
            options={
                'db_table': 'secret_versions',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SecretProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_project', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'secret_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecretEnvironment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide from UI (for system-managed secrets)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='secretmanager.secretproject')),
            ],
            options={
                'db_table': 'secret_environments',
                'ordering': ['position', 'name'],
                'unique_together': {('project', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='secret',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='secretmanager.secretenvironment'),
        ),
        migrations.AddField(
            model_name='secret',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_secrets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together={('environment', 'key')},
        ),
    ]
