# Generated by Django 4.2.7 on 2025-11-12 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagebuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('build_type', models.CharField(choices=[('nocode', 'No-Code Builder'), ('import', 'Import Existing')], default='nocode', max_length=10)),
                ('frontend_framework', models.CharField(choices=[('react', 'React'), ('vue', 'Vue'), ('angular', 'Angular'), ('static', 'Static HTML/CSS')], default='react', max_length=20)),
                ('frontend_dist_path', models.CharField(blank=True, help_text='Path to built frontend files', max_length=500)),
                ('frontend_dev_path', models.CharField(blank=True, help_text='Path to source/editable files', max_length=500)),
                ('backend_path', models.CharField(blank=True, help_text='Path to backend folder', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='DomainConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('dns_verified', models.BooleanField(default=False)),
                ('expected_ip', models.GenericIPAddressField(help_text='Server IP that domain should point to')),
                ('actual_ip', models.GenericIPAddressField(blank=True, help_text='Current A-record IP', null=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ssl_auto', models.BooleanField(default=True, help_text="Use Let's Encrypt for SSL")),
                ('ssl_cert_path', models.CharField(blank=True, max_length=500)),
                ('ssl_key_path', models.CharField(blank=True, max_length=500)),
                ('nginx_config_path', models.CharField(blank=True, help_text='Path to generated NGINX config', max_length=500)),
                ('nginx_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain_config', to='pagebuilder.project')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating Files'), ('configuring', 'Configuring Services'), ('starting_backend', 'Starting Backend'), ('deploying_frontend', 'Deploying Frontend'), ('applying_nginx', 'Applying NGINX Config'), ('success', 'Success'), ('failed', 'Failed'), ('rollback', 'Rolled Back')], default='pending', max_length=20)),
                ('logs', models.TextField(blank=True, help_text='Deployment logs and output')),
                ('frontend_hash', models.CharField(blank=True, help_text='Git hash or checksum of frontend', max_length=64)),
                ('backend_hash', models.CharField(blank=True, help_text='Git hash or checksum of backend', max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='pagebuilder.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('component_json', models.JSONField(help_text='JSON representation of component structure')),
                ('preview_image', models.CharField(blank=True, help_text='Path to preview thumbnail', max_length=500)),
                ('category', models.CharField(default='custom', max_length=100)),
                ('tags', models.JSONField(default=list, help_text='Tags for component search')),
                ('is_public', models.BooleanField(default=False, help_text='Share with other users')),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackendConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('django', 'Django'), ('fastapi', 'FastAPI'), ('nodejs', 'Node.js'), ('other', 'Other')], max_length=20)),
                ('detected_apis', models.JSONField(default=list, help_text='List of detected API endpoints')),
                ('detected_models', models.JSONField(default=list, help_text='List of detected data models/schemas')),
                ('start_command', models.CharField(help_text='Command to start backend server', max_length=500)),
                ('port', models.IntegerField(default=8000, help_text='Backend server port')),
                ('environment_vars', models.JSONField(default=dict, help_text='Environment variables for backend')),
                ('process_id', models.IntegerField(blank=True, help_text='PID of running backend process', null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('last_started', models.DateTimeField(blank=True, null=True)),
                ('last_stopped', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backend_config', to='pagebuilder.project')),
            ],
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.FloatField(default=1.0, help_text='Animation duration in seconds')),
                ('keyframes_json', models.JSONField(help_text='Keyframe definitions with CSS properties')),
                ('easing', models.CharField(default='ease', help_text='CSS easing function', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='API endpoint path (e.g., /api/users)', max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('request_schema', models.JSONField(default=dict, help_text='Expected request body schema')),
                ('response_schema', models.JSONField(default=dict, help_text='Expected response schema')),
                ('requires_auth', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backend_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_endpoints', to='pagebuilder.backendconfig')),
            ],
            options={
                'unique_together': {('backend_config', 'path', 'method')},
            },
        ),
    ]
